### ISSUE TITLE
[Fabric][1.16 Snapshot 20w18a] Invisible shield

### ISSUE THREAD

**Issue by Omni35** [NinjaPhenix/FabricMods#10]
So it appears the shield doesn't render with this mod, it works fine just doesn't show.

Used with:
**Fabric:** fabric-loader-0.8.2+build.194-20w18a
**Fabric API:** fabric-api-0.10.1+build.336-1.16
**Mod version:** expandedstorage-4.12.40+20w18a
**Log:** https://gist.github.com/Omni35/4fc8b18ef2dd90af6a8de78292b1948f

![2020-05-02_20 25 55](https://user-images.githubusercontent.com/7506611/80872923-51f1ed00-8cb5-11ea-8b0e-319741e28ad0.png)
![2020-05-02_20 26 04](https://user-images.githubusercontent.com/7506611/80872942-6df58e80-8cb5-11ea-9bae-eba11d0b923f.png)

**Comment by NinjaPhenix** [comment]
Thanks for making an issue, didn't realise I left some testing code in before releasing the mod, will have a new version out in a few minutes.

**Comment by NinjaPhenix** [comment]
Fixed, available here: https://www.curseforge.com/minecraft/mc-mods/expanded-storage-fabric/files/2946680
