### ISSUE TITLE
Creative Button Mover crashes game up picking up first block (1.16 20w20b)

### ISSUE THREAD

**Issue by matthew-cline** [NinjaPhenix/FabricMods#17]
In Minecraft 1.16 20w20b, in a newly generated world, upon picking up the first wood block the game crashes, and the report says that it's due to Create Button Mover, which is embedded in Expanded Storage.  See [this crash report](https://github.com/NinjaPhenix/FabricMods/files/4637902/crash.txt), though the critical line in the report seems to be this:

> Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on tick could not find any targets matching 'Lnet/minecraft/class_481;method_25431()V' in net.minecraft.class_481. Using refmap creativebuttonmover-refmap.json [PREINJECT Applicator Phase -> creativebuttonmover.mixins.client.json:CreativeInventoryScreenMixin -> Prepare Injections ->  -> handler$zgh001$tick(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]

**Comment by NinjaPhenix** [comment]
For some reason the generated refmap broken, will release a new build in a few minutes.

**Comment by NinjaPhenix** [comment]
Fixed in latest build: https://www.curseforge.com/minecraft/mc-mods/expanded-storage-fabric/files/2958230
