### ISSUE TITLE
Crash When trying to open NonCorerlatedExtras in 1.16 release candiadate 1

### ISSUE THREAD

**Issue by Lukeplayswastaken** [NinjaPhenix/FabricMods#32]
Could not find required mod: noncorrelatedextras requires {fabricloader @ [>=${dep_loader_version}]} when trying to open NonCorrelatedItems in the 1.16 release candidate .
![image](https://user-images.githubusercontent.com/51130586/85403496-14099a80-b57b-11ea-9f5a-16036db47fca.png)

**Comment by NinjaPhenix** [comment]
Can you download the mod from curseforge: https://www.curseforge.com/minecraft/mc-mods/noncorrelatedextras/files/2986452, the file there doesn't have the replacment token inside.

**Comment by NinjaPhenix** [comment]
Just figured out this is when installing the sources jar as a mod, these jars are not for users.
