### ISSUE TITLE
Chests appear to have lighting issues 1.16

### ISSUE THREAD

**Issue by Processhf** [NinjaPhenix/FabricMods#36]
When looking at any metallic chest with the exception of netherite chests, the lighting/texture of the chests sort of flickers.

http://puu.sh/FZNbk/8a77ee3d97.mp4

**Comment by NinjaPhenix** [comment]
Thanks for making this issue, I actually forgot about this bug.

Essentially both halves of the chest are rendering the whole chest, I need to split the code & textures into left / right half.

**Comment by Processhf** [comment]
Any update on this? I tried messing with the textures and the way it renders them to no avail. It will constantly Z-fight on every different type of chest except single chests

**Comment by NinjaPhenix** [comment]
I'm going to have to rewrite the rendering to fix this issue, will look into it today.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by NinjaPhenix** [comment]
Got the issue fixed, just need to update all the chest assets, will probably get an update out tomorrow.

**Comment by NinjaPhenix** [comment]
Fixed in build 5.3.12: https://www.curseforge.com/minecraft/mc-mods/expanded-storage-fabric/files/2993185
