### ISSUE TITLE
Non-Corrolated Extras 0.3.1 for MC 1.16.1 crashes during startup.

### ISSUE THREAD

**Issue by JillSwift** [NinjaPhenix/FabricMods#42]
Launched with MultiMC 5, 0.6.12.
Minecraft doesn't even get to the loading screen.

Logs:
https://paste.ee/p/TAIAa

I beg pardon if I've posted this in the wrong repo.

**Comment by NinjaPhenix** [comment]
My bad, I pulled an early version of trinket off Github cause there were class renames, seems like there were more changes, will release a fix soon.

**Comment by NinjaPhenix** [comment]
Should be fixed in 0.3.2: https://www.curseforge.com/minecraft/mc-mods/noncorrelatedextras/files/2991995

**Comment by JillSwift** [comment]
0.3.2 works wonderfully. Thank you!
