### ISSUE TITLE
Nbt is often way to long to fit on screen

### ISSUE THREAD

**Issue by Kroppeb** [NinjaPhenix/FabricMods#44]
NinjiTips allows a user to see what nbt there is on an item, however this can get very long very quickly

**Comment by NinjaPhenix** [comment]
I had removed the tooltip wrapping in favour of tooltip autowrap which did a better job. Will look at reimplementing a better version but for now you can link the item in chat and then click the item to copy it's NBT.

**Comment by Kroppeb** [comment]
tooltip autowrap seems to be stuck on 1.15 sadly. I'm not sure what you mean with "click the item in chat"

**Comment by NinjaPhenix** [comment]
You can link an item into chat by pressing `Shift+T` whilst hovering over an item.
Then you should be able to click the `[Item Name]` that appears in chat to copy its nbt data to your clipboard.

**Comment by NinjaPhenix** [comment]
Closing this as I'm no longer supporting that mod.
