### ISSUE TITLE
Renaming chests crashes game

### ISSUE THREAD

**Issue by Processhf** [NinjaPhenix/FabricMods#48]
https://pastebin.com/ikqNfuJE

Happens on any ExpandedStorage chest

**Comment by NinjaPhenix** [comment]
Odd this only crashes outside of development, will get it fixed relatively soon.

**Comment by NinjaPhenix** [comment]
Fixed in 5.3.15: https://www.curseforge.com/minecraft/mc-mods/expanded-storage-fabric/files/3001099 ( might still be pending )
