### ISSUE TITLE
Error loading minecraft

### ISSUE THREAD

**Issue by Darkenwolf2050** [NinjaPhenix/FabricMods#51]
error only happens when loading with expanded storage mod. Other mods all load correctly until ES mod added the mods folder.
paste bin to crash report [here](https://pastebin.com/PXq3DgzW)

**Comment by NinjaPhenix** [comment]
Seems to be a conflict between mine and sandwichables' mixins since we mixin to the same class, will see if there is anything I can do on my end to fix this.

**Comment by NinjaPhenix** [comment]
Just looked at sandwichables' mixin and I won't be able to fix this on my end. Please report to sandwichable instead.

**Comment by Darkenwolf2050** [comment]
I'll see if sandwichable can fix it. your mod and thiers worked OK until Optifine and optifabric were added. After that neither inms, expanded storage or sandwichable worked.

**Comment by Darkenwolf2050** [comment]
Thanks for looking into this so quickly. These mods are really good but if it's them or shaders I'll have to choose shaders.
I have tried each mod (inms, expanded storage and sandwichable) separately (with optifine and the other listed) and they always fail either on their own or together.

**Comment by NinjaPhenix** [comment]
Going to close this as it is likely not an issue with expanded storage but some incompatibility brought up by optifine which I won't be supporting as there isn't an easy way to do so as it is closed sourced.
