### ISSUE TITLE
Game crashed when clicking button "Change screen type" at old netherite chest

### ISSUE THREAD

**Issue by linzexin022** [NinjaPhenix/FabricMods#52]
Hi there, the game crashed when I was clicking the "Change screen type" button at old netherite chest GUI, and here's the screenshot and game log:

-------------------------------------------------------------------------------------------here👇
![2020-08-07_10 41 00](https://user-images.githubusercontent.com/59003232/89603021-b4e9b600-d89a-11ea-8acc-c7c979650b44.png)

[crash-2020-08-07_10.26.06-client.txt](https://github.com/NinjaPhenix/FabricMods/files/5039038/crash-2020-08-07_10.26.06-client.txt)

**Comment by NinjaPhenix** [comment]
Sorry for a bit of a wait on a reply but honestly I have no clue what's causing this issue as the method which is causing the crash is a vanilla one. 

I will look into the issue though.

**Comment by NinjaPhenix** [comment]
Spent a good chunk of time today trying to find the cause of this issue but couldn't find anything expanded storage related or otherwise with may cause this issue.

I am also unable to reproduce this issue so this issue likely won't get fixed unless I encounter it in a reproducible fashion.

**Comment by linzexin022** [comment]
Thank you for your attention in this matter. This is my own modpack, to be honest, I have the habit of updating mods frequently, so I may not be able to reproduce it... I think it's not a big deal so if it doesn't happen to anyone else, I will not force you to fix this unreproducable problem. Thank you again for taking much time on it! May you have a nice day!
