### ISSUE TITLE
NonCorrelatedExtras and Connected Block Textures cause a crash when loaded together 

### ISSUE THREAD

**Issue by NeRdTheNed** [NinjaPhenix/FabricMods#53]
Reproducible by using these versions (the latest versions at time of writing) of [Connected Block Textures](https://www.curseforge.com/minecraft/mc-mods/connected-block-textures/files/3026024), [NonCorrelatedExtras](https://www.curseforge.com/minecraft/mc-mods/noncorrelatedextras/files/2991995), and the [Fabric API](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3026258). [Example crash log](https://paste.ee/p/awfqD).

**Comment by NinjaPhenix** [comment]
NonCorrelatedExtras is indeed causing this issue, I'll fix this issue however keep in mind I'm not officially supporting this mod anymore.

**Comment by NinjaPhenix** [comment]
New build can be found here once approved: https://www.curseforge.com/minecraft/mc-mods/noncorrelatedextras/files/3027138

**Comment by NeRdTheNed** [comment]
Thank you very much for fixing this!
