### ISSUE TITLE
Translated into Russian

### ISSUE THREAD

**Issue by Miros77** [NinjaPhenix/FabricMods#57]
[ru_ru.zip](https://github.com/NinjaPhenix/FabricMods/files/5081463/ru_ru.zip)

**Comment by NinjaPhenix** [comment]
Added in https://github.com/NinjaPhenix/FabricMods/commit/ba96d24bfd434eebd8a7581943aec10a7f863824,
will have a jar out shortly with them included.

**Comment by NinjaPhenix** [comment]
Released in https://www.curseforge.com/minecraft/mc-mods/expanded-storage-fabric/files/3034772, thanks for providing translations.
