### ISSUE TITLE
5.5.21+1.16.2 : Server Crash - NoClassDefFoundError: net/minecraft/server/network/ServerPlayerEntity

### ISSUE THREAD

**Issue by Katorone** [NinjaPhenix/FabricMods#59]
[latest.log](https://github.com/NinjaPhenix/FabricMods/files/5105305/latest.log)

**Comment by NinjaPhenix** [comment]
Fixed in 5.5.22: https://www.curseforge.com/minecraft/mc-mods/expanded-storage-fabric/files/3037948

**Comment by Katorone** [comment]
Thanks !
