### ISSUE TITLE
Expanded Storage and Pipe Mod Issues

### ISSUE THREAD

**Issue by JoshMayberry** [NinjaPhenix/FabricMods#62]
I have been using your Expanded Storage mod in conjunction with [EZPaS](https://www.curseforge.com/minecraft/mc-mods/ezpas/) for our item sorter/storage solution.

The two mods worked well together, but after I updated from version 5.3.14+1.16 to 5.5.22+1.16.1, the expanded storage chests stopped working with the pipe system.
Perhaps a change was made between those two versions that made your chests stop working with the pipes?

**Comment by NinjaPhenix** [comment]
Seems like the pullers are only pulling out of the chest they are attached to and not the whole inventory, will see if there's anything I can do on my end to fix this.

**Comment by NinjaPhenix** [comment]
This issue was also fixed by 27fe7d0645a8564588ced0b50e09d961592239e6, would like to get some more issues fixed before another release.

**Comment by NinjaPhenix** [comment]
Fixed in https://www.curseforge.com/minecraft/mc-mods/expanded-storage-fabric/files/3043410
