### ISSUE TITLE
Incompatibility: Expanded Storage 5.5.22+1.16.1 and Torcherino 2.11.67+1.16/rc1 (embedded Chainmail issue)

### ISSUE THREAD

**Issue by rxay579** [NinjaPhenix/FabricMods#66]
Using the versions mentioned in the title causes the client to crash on launch.
I did some simple testing and it appears that the embedded version of chainmail (v0.5.0) in the newer Expanded Storage is causing the issue.
Using an older version of Expanded Storage (expandedstorage-5.3.16+1.16) allows ES and Torcherino to work together.
The older ES mentioned has chainmail v0.3.0 embedded, so the issue seems to have come in somewhere between chainmail v0.3.0 and v0.5.0.

Hope this is fixable within 1.16.1 as 1.16.2 changes have held up some Fabric mods.

Crash log attached
[crash-log.txt](https://github.com/NinjaPhenix/FabricMods/files/5144734/crash-log.txt)

The repos for Torcherino and Chainmail are both marked as "archived", so I couldn't report there.

**Comment by NinjaPhenix** [comment]
This is the correct place to report as it's the repo where I maintain all my fabric mods.

I'll release a new version for 1.16.1 soon.

**Comment by rxay579** [comment]
Thanks.  Will check them out next chance I get.
