### ISSUE TITLE
Add option to disable Old Chests

### ISSUE THREAD

**Issue by alxpettit** [NinjaPhenix/FabricMods#70]
I'd like to build a minimal modpack with this mod, but the old chests add another set of unused stuff. Ideally there'd be an option to disable them.

**Comment by NinjaPhenix** [comment]
You can disable the recipes for these blocks using a custom datapack, recipe advancements can also be disabled by adding `minecraft:impossible` to the criteria list.

Having the blocks removed entirely is something I don't plan on supporting as the existing solution provided by minecraft is better.

**Comment by alxpettit** [comment]
Aww, that's a shame. Well, thanks for the response. Guess I have to learn to use datapacks now. :P
