### ISSUE TITLE
[Bug] Endless chest upgrade item

### ISSUE THREAD

**Issue by Medwokee** [NinjaPhenix/FabricMods#75]
**Describe the bug**
Chest upgrade item doesnt disappear when used on a large chest

**Imgur GIF:** [tap](https://imgur.com/a/sRVqfSe) 

**Environment:**
* Minecraft version: 1.16.3
* Mod Loader: fabric-loader-0.9.3+build.207-1.16.3, fabric-api-0.22.0+build.408-1.16, expandedstorage-5.6.29+1.16.2 (1.16.3).

**Comment by vegeta897** [comment]
Just discovered this too, with the iron upgrade.

**Comment by NinjaPhenix** [comment]
Will look into / fix shortly. Thanks for bringing this to my attention.

**Comment by NinjaPhenix** [comment]
Can be downloaded here once approved: https://www.curseforge.com/minecraft/mc-mods/expanded-storage-fabric/files/3068922

**Comment by NinjaPhenix** [comment]
Had to rebuild cause of loom, jar can be found here instead: https://www.curseforge.com/minecraft/mc-mods/expanded-storage-fabric/files/3068933
