### ISSUE TITLE
tooltips

### ISSUE THREAD

**Issue by stefment** [NinjaPhenix/FabricMods#80]
![2020-11-16_15 18 08](https://user-images.githubusercontent.com/8888420/99263134-14068180-281f-11eb-863b-8e7bdd36582e.png)

The iron upgrade works with barrels too it seems but not immediately clear from the tooltip.

**Comment by NinjaPhenix** [comment]
Sorry for late reply, will get this fixed in next update but it will be a while until it its out, atleast a month.

**Comment by NinjaPhenix** [comment]
Fixed in dev, going to look into a crash that was reported before releasing.

**Comment by NinjaPhenix** [comment]
Fixed in 5.6.32. https://www.curseforge.com/minecraft/mc-mods/expanded-storage-fabric/files/3175545
