### ISSUE TITLE
Fat xp orbs go negative possibly when value overflows

### ISSUE THREAD

**Issue by ImJustMatt** [NinjaPhenix/FabricMods#82]
We probably don't expect xp to ever get that large, but when used in combination with Cursed Dirt from Kibe, it's possible for xp to pool up to the point where you get an xp orb that exceeds the maximum integer value. When this occurs, and the entity is saved to the world data, it will causes the server to crash when the Kibe Vacuum Hopper tries to access this (negative) xp orb.

Here's a screenshot for example
https://cdn.discordapp.com/attachments/577535257356664845/783738840757567518/unknown.png

**Comment by NinjaPhenix** [comment]
Fixed in 0.0.8, experience orbs are now capped to Integer.MAX_VALUE ( 2^31 - 1 ), any extra experience is voided.
https://www.curseforge.com/minecraft/mc-mods/fat-experience-orbs/files/3128731
