### ISSUE TITLE
Expanded Storage Long Chest Texture Glitch

### ISSUE THREAD

**Issue by AlexisDot** [NinjaPhenix/FabricMods#83]
In the process of making textures for Expanded Storage to fit in with the Texturepack I am playing I noticed some glitch in the long chest textures. 

The back part is blurry and also flickers when moving around it. The glitch is also there in your original texture if not as  noticeabe, due to this i added a screenshot of my edited textures as a showcase aswell.

![2020-12-17 14_17_56-Minecraft_ 1 16 2 - Singleplayer](https://user-images.githubusercontent.com/19834703/102493578-aba3fd80-4073-11eb-86dc-55db01fe252f.png)
![2020-12-17 14_23_43-Minecraft_ 1 16 2 - Singleplayer](https://user-images.githubusercontent.com/19834703/102493581-acd52a80-4073-11eb-8e07-d1a70b771e99.png)
 
 Have a nice christmas and smooth progress for your assignments, until next year ;)

**Comment by NinjaPhenix** [comment]
Odd I don't think I've ever noticed this. 
Have you resized the back texture by any chance to not be a multiple of 48x48?
If not do you have any graphic related mods e.g. Canvas, Sodium, Optifine ect which could be altering the way it's rendered?
Tbh I'm not quite sure what to ask as I don't know how any issue would affect that one specific model.

**Comment by AlexisDot** [comment]
Ah  gdi, now i'm embarassed since i frogging didn't check optifine... my bad, forget this was here, not an issue on your end.

~~as a programmer (not mc modder) this makes me feel very stupid...~~
