### ISSUE TITLE
Opening a combined old chest crashes my game.

### ISSUE THREAD

**Issue by KidlatSV** [NinjaPhenix/FabricMods#84]
[crash-2021-01-15_16.59.01-client.txt](https://github.com/NinjaPhenix/FabricMods/files/5819436/crash-2021-01-15_16.59.01-client.txt)

**Comment by NinjaPhenix** [comment]
Can you try to reproduce this issue with https://www.curseforge.com/minecraft/mc-mods/mixintrace installed. Will take a closer look into the issue on the 20th.

**Comment by NinjaPhenix** [comment]
Crashing atleast should be fixed in 5.6.32, it's possible still that the screen won't render but there's nothing I can do about that.
