### ISSUE TITLE
Stuck on pick layout with Servux 0.1.5

### ISSUE THREAD

**Issue by Ninja202** [NinjaPhenix/FabricMods#86]
When opening a chest on a 1.16.5 server i get stuck on the pick layout screen and have to kick myself. Versions of the mod that worked on 1.16.4 also do this, and it works normally in singleplayer.

**Comment by NinjaPhenix** [comment]
That's odd as practically nothing affecting the mod should have changed in 1.16.5, will try to reproduce myself.

**Comment by NinjaPhenix** [comment]
Can't seem to reproduce with only expanded storage installed using a dedicated server + client ( on same machine ).

**Comment by Ninja202** [comment]
I think it might be a incompatibility, i will try and narrow down what it could be

**Comment by Ninja202** [comment]
After more testing i have found that this is an incompatibility with Servux 0.1.5 specificaly, it works just fine with Servux 0.1.3.

**Comment by NinjaPhenix** [comment]
Good to know, will keep this issue open until it is fixed on Servux's side.

**Comment by Ninja202** [comment]
This Seems to have been fixed with Servux 0.1.6 So im closing this issue.
