### ISSUE TITLE
GUI of Expanded Containers

### ISSUE THREAD

**Issue by DaarkDev** [NinjaPhenix/FabricMods#90]
Hello! This is just a "quality of life" issue, but really bothers me in the sense of OCD and all that. I am using a dark UI texture pack, but it does not apply to the containers in the mod. Because of this, vanilla chests and containers have dark UI's, but the ones in this mod do not. If you can, please implement support for this.

Thanks!

**Comment by NinjaPhenix** [comment]
All the UI textures for chests can currently be found at https://github.com/NinjaPhenix/FabricMods/tree/1.16.5/expandedstorage/src/main/resources/assets/expandedstorage/textures/gui/
You can make a resource packs to recolour them however you wish, should be pretty simple, just copy the textures into the dark UI resource pack or create your own resource pack and then recolour them in a paint software which supports alpha transparency. ( not mspaint if you use windows )

**Comment by DaarkDev** [comment]
I don't know how to make a texture pack or actually do any of that, but I will try to find a tutorial. Thanks!

**Comment by DaarkDev** [comment]
Not sure how to recolor them, but thanks for the help anyways.

**Comment by NinjaPhenix** [comment]
If you'd like I can create a dark theme resource pack if you can provide a sample of the original dark theme texture pack.

**Comment by DaarkDev** [comment]
That would be really nice, and might help some other people out too! You can either add me on discord: Daark#8745
or I can attempt to send over the resource pack here.

**Comment by NinjaPhenix** [comment]
Can't seem to add on discord but all I need is an image of one of the screens or a link to the resource pack.

**Comment by DaarkDev** [comment]
Oh, sorry about that, should be working now as it was one of the settings. If you still want to add me for coordination, that works as well. Here is the link (It came from vanilla tweaks): https://vanillatweaks.net/share#helvHC

**Comment by NinjaPhenix** [comment]
Here's a vanillatweaks style dark theme, enjoy, note: only includes american english translations, if you need others ( which are provided by expanded storage already ) please let me know.
[ExpandedStorageDarkTheme_1.zip](https://github.com/NinjaPhenix/FabricMods/files/6176595/ExpandedStorageDarkTheme_1.zip)

**Comment by DaarkDev** [comment]
Thanks so much! Works great, and is a huge improvement to my style since the GUI's are all dark now. :D
