### ISSUE TITLE
failed to launch

### ISSUE THREAD

**Issue by TomerGamerTV** [NinjaPhenix/FabricMods#91]
![image](https://user-images.githubusercontent.com/44266242/113861715-2e320380-97b0-11eb-9db0-d1a0e47758f8.png)
how do i fix it?

**Comment by NinjaPhenix** [comment]
You need to install Fabric API: https://www.curseforge.com/minecraft/mc-mods/fabric-api

If you are using 1.16.5 then here's the latest version ( as of 7th April 2021 ): https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3248105
